# Generated by Django 3.1.7 on 2021-03-11 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HseNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('id_number', models.PositiveIntegerField()),
                ('mobile_number', models.PositiveIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spveapp.gender')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spveapp.position')),
            ],
        ),
        migrations.CreateModel(
            name='Occupants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spveapp.gender')),
                ('hse_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spveapp.hsenumber')),
            ],
        ),
        migrations.CreateModel(
            name='HseOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('id_number', models.PositiveIntegerField()),
                ('mobile_number', models.PositiveIntegerField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spveapp.gender')),
                ('hse_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spveapp.hsenumber')),
            ],
        ),
    ]
